/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/ai-conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ai Conversation
         * @description 读取属于当前用户的完整多轮对话。
         */
        get: operations["get_ai_conversation_api_v1_ai_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai-conversations/{conversation_id}/messages/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stream Ai Conversation Message
         * @description 用 SSE 实时发送 Codex Skill 状态和逐段回复。
         */
        post: operations["stream_ai_conversation_message_api_v1_ai_conversations__conversation_id__messages_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Password Reset
         * @description 统一接受重置请求，存在账户时通过适配器发送单次链接。
         */
        post: operations["request_password_reset_api_v1_auth_password_reset_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-resets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Password
         * @description 消费单次令牌设置新密码，并撤销用户现有会话。
         */
        post: operations["reset_password_api_v1_auth_password_resets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/registrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description 创建邮箱密码用户，并保证响应不包含密码或摘要。
         */
        post: operations["register_api_v1_auth_registrations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current Session
         * @description 从服务端不透明会话恢复当前用户身份。
         */
        get: operations["current_session_api_v1_auth_session_get"];
        put?: never;
        post?: never;
        /**
         * Logout
         * @description 幂等撤销当前会话并清除浏览器 Cookie。
         */
        delete: operations["logout_api_v1_auth_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description 验证邮箱密码、轮换旧会话并写入环境匹配的安全 Cookie。
         */
        post: operations["login_api_v1_auth_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live
         * @description 返回固定存活状态，供容器和反向代理探测进程。
         */
        get: operations["live_api_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description 根据数据库探测结果返回可供流量入口使用的就绪状态。
         */
        get: operations["ready_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Instruments
         * @description 按代码或名称分页搜索当前一期支持的股票和基金。
         */
        get: operations["search_instruments_api_v1_instruments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments/{instrument_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Instrument
         * @description 返回指定一期资产及各价格口径的最新本地快照。
         */
        get: operations["get_instrument_api_v1_instruments__instrument_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments/{instrument_id}/ai-analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ai Analysis
         * @description 读取最近报告；尚无报告返回空值，不产生新的模型费用。
         */
        get: operations["get_ai_analysis_api_v1_instruments__instrument_id__ai_analysis_get"];
        put?: never;
        /**
         * Generate Ai Analysis
         * @description 刷新真实历史数据并手动生成或覆盖最近报告。
         */
        post: operations["generate_ai_analysis_api_v1_instruments__instrument_id__ai_analysis_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments/{instrument_id}/ai-conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Ai Conversation
         * @description 为持仓或自选中的标的创建一个新的 Codex Session。
         */
        post: operations["create_ai_conversation_api_v1_instruments__instrument_id__ai_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments/{instrument_id}/ai-conversations/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Latest Ai Conversation
         * @description 读取当前用户指定标的最近一次多轮会话。
         */
        get: operations["get_latest_ai_conversation_api_v1_instruments__instrument_id__ai_conversations_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market-data/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Market Data Schedule
         * @description 返回后台 Worker 当前使用的定时任务配置。
         */
        get: operations["get_market_data_schedule_api_v1_market_data_schedule_get"];
        /**
         * Update Market Data Schedule
         * @description 更新后台 Job 频率，Worker 最迟十秒内检测版本并重新排期。
         */
        put: operations["update_market_data_schedule_api_v1_market_data_schedule_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market-data/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Market Data Status
         * @description 返回每种已运行同步任务的最近状态，不在请求内访问行情源。
         */
        get: operations["get_market_data_status_api_v1_market_data_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market-data/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Manually Sync Market Data
         * @description 复用 Worker 同步服务立即运行指定任务，并返回任务最终状态。
         */
        post: operations["manually_sync_market_data_api_v1_market_data_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/position-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Position Summary
         * @description 返回全部分组或指定分组的持仓汇总。
         */
        get: operations["get_position_summary_api_v1_position_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Positions
         * @description 分页返回当前用户全部或指定分组的持仓。
         */
        get: operations["list_positions_api_v1_positions_get"];
        put?: never;
        /**
         * Create Position
         * @description 按录入模式为当前用户分组创建唯一股票或基金持仓。
         */
        post: operations["create_position_api_v1_positions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/positions/{position_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Position
         * @description 返回当前用户拥有的指定持仓。
         */
        get: operations["get_position_api_v1_positions__position_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Position
         * @description 删除当前用户指定持仓。
         */
        delete: operations["delete_position_api_v1_positions__position_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Position
         * @description 按录入模式和版本部分修改持仓或移动分组。
         */
        patch: operations["update_position_api_v1_positions__position_id__patch"];
        trace?: never;
    };
    "/api/v1/watchlist-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Watchlist Groups
         * @description 返回当前用户全部自选分组及标的数量。
         */
        get: operations["list_watchlist_groups_api_v1_watchlist_groups_get"];
        put?: never;
        /**
         * Create Watchlist Group
         * @description 为当前用户创建名称唯一的普通自选分组。
         */
        post: operations["create_watchlist_group_api_v1_watchlist_groups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlist-groups/{group_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Watchlist Group
         * @description 返回当前用户拥有的指定自选分组。
         */
        get: operations["get_watchlist_group_api_v1_watchlist_groups__group_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Watchlist Group
         * @description 删除当前用户的普通空分组。
         */
        delete: operations["delete_watchlist_group_api_v1_watchlist_groups__group_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Watchlist Group
         * @description 按版本重命名或调整当前用户自选分组排序。
         */
        patch: operations["update_watchlist_group_api_v1_watchlist_groups__group_id__patch"];
        trace?: never;
    };
    "/api/v1/watchlist-groups/{group_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Watchlist Items
         * @description 分页返回当前用户指定分组的观察标的与本地行情。
         */
        get: operations["list_watchlist_items_api_v1_watchlist_groups__group_id__items_get"];
        put?: never;
        /**
         * Create Watchlist Item
         * @description 向当前用户指定分组添加股票或基金。
         */
        post: operations["create_watchlist_item_api_v1_watchlist_groups__group_id__items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlist-items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Watchlist Item
         * @description 返回当前用户拥有的指定观察标的。
         */
        get: operations["get_watchlist_item_api_v1_watchlist_items__item_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Watchlist Item
         * @description 删除当前用户指定观察标的。
         */
        delete: operations["delete_watchlist_item_api_v1_watchlist_items__item_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Watchlist Item
         * @description 按版本移动观察标的、修改备注或调整排序。
         */
        patch: operations["update_watchlist_item_api_v1_watchlist_items__item_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AIAnalysisResponse
         * @description 返回最近一次结构化 AI 分析及其数据溯源。
         */
        AIAnalysisResponse: {
            /** Actions */
            actions: string[];
            conclusion: components["schemas"]["AnalysisConclusion"];
            /** Dataasof */
            dataAsOf: string;
            /** Datasources */
            dataSources: string[];
            /**
             * Disclaimer
             * @default 仅供个人研究参考，不构成投资建议。
             */
            disclaimer: string;
            /**
             * Generatedat
             * Format: date-time
             */
            generatedAt: string;
            /** Highlights */
            highlights: string[];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            instrument: components["schemas"]["AnalysisInstrumentResponse"];
            /** Metrics */
            metrics: components["schemas"]["AnalysisMetricResponse"][];
            /** Model */
            model: string;
            /** Provider */
            provider: string;
            /** Risks */
            risks: string[];
            /** Summary */
            summary: string;
        };
        /**
         * AIConversationMessageCreate
         * @description 校验用户发送给 Agent 的单轮文本。
         */
        AIConversationMessageCreate: {
            /** Content */
            content: string;
        };
        /**
         * AIConversationMessageResponse
         * @description 返回一条已保存或正在生成的对话消息。
         */
        AIConversationMessageResponse: {
            /** Content */
            content: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            role: components["schemas"]["AIMessageRole"];
            status: components["schemas"]["AIMessageStatus"];
        };
        /**
         * AIConversationResponse
         * @description 返回当前用户独立的 Codex 会话及完整消息。
         */
        AIConversationResponse: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            instrument: components["schemas"]["AnalysisInstrumentResponse"];
            /** Messages */
            messages: components["schemas"]["AIConversationMessageResponse"][];
            status: components["schemas"]["AIConversationStatus"];
            /** Title */
            title: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /**
         * AIConversationStatus
         * @description 表示一个会话当前是否可接受下一轮消息。
         * @enum {string}
         */
        AIConversationStatus: "IDLE" | "RUNNING" | "FAILED";
        /**
         * AIMessageRole
         * @description 区分用户输入和 Agent 回复。
         * @enum {string}
         */
        AIMessageRole: "USER" | "ASSISTANT";
        /**
         * AIMessageStatus
         * @description 记录单条消息是否仍在生成或已经结束。
         * @enum {string}
         */
        AIMessageStatus: "STREAMING" | "COMPLETED" | "FAILED";
        /**
         * AnalysisConclusion
         * @description 用中性研究结论替代确定性买卖指令。
         * @enum {string}
         */
        AnalysisConclusion: "POSITIVE" | "NEUTRAL" | "CAUTIOUS" | "INSUFFICIENT_DATA";
        /**
         * AnalysisInstrumentResponse
         * @description 返回分析结果对应的稳定资产身份。
         */
        AnalysisInstrumentResponse: {
            assetType: components["schemas"]["AssetType"];
            currency: components["schemas"]["Currency"];
            exchange: components["schemas"]["Exchange"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            market: components["schemas"]["Market"];
            /** Name */
            name: string;
            /** Ticker */
            ticker: string;
        };
        /**
         * AnalysisMetricResponse
         * @description 返回页面直接展示的一项已计算指标。
         */
        AnalysisMetricResponse: {
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /**
         * AssetType
         * @description 区分一期支持的股票与基金。
         * @enum {string}
         */
        AssetType: "STOCK" | "FUND";
        /**
         * CostInputMode
         * @description 表示用户直接输入总成本或平均成本。
         * @enum {string}
         */
        CostInputMode: "TOTAL_COST" | "AVERAGE_COST";
        /**
         * CreateFundAmountPositionRequest
         * @description 接收基金当前金额和可正可负的持有收益。
         */
        CreateFundAmountPositionRequest: {
            /** Currentvalue */
            currentValue: string;
            /**
             * Groupid
             * Format: uuid
             */
            groupId: string;
            /** Holdingprofit */
            holdingProfit: string;
            /**
             * Inputdate
             * Format: date
             */
            inputDate: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            inputMode: "FUND_AMOUNT";
            /**
             * Instrumentid
             * Format: uuid
             */
            instrumentId: string;
        };
        /**
         * CreateFundSharesPositionRequest
         * @description 接收基金份额及总成本或平均成本二选一输入。
         */
        CreateFundSharesPositionRequest: {
            /** Averagecost */
            averageCost?: string | null;
            costInputMode: components["schemas"]["CostInputMode"];
            /**
             * Groupid
             * Format: uuid
             */
            groupId: string;
            /**
             * Inputdate
             * Format: date
             */
            inputDate: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            inputMode: "FUND_SHARES";
            /**
             * Instrumentid
             * Format: uuid
             */
            instrumentId: string;
            /** Quantity */
            quantity: string;
            /** Totalcost */
            totalCost?: string | null;
        };
        /**
         * CreateStockPositionRequest
         * @description 接收股票数量及总成本或平均成本二选一输入。
         */
        CreateStockPositionRequest: {
            /** Averagecost */
            averageCost?: string | null;
            costInputMode: components["schemas"]["CostInputMode"];
            /**
             * Groupid
             * Format: uuid
             */
            groupId: string;
            /**
             * Inputdate
             * Format: date
             */
            inputDate: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            inputMode: "STOCK_SHARES";
            /**
             * Instrumentid
             * Format: uuid
             */
            instrumentId: string;
            /** Quantity */
            quantity: string;
            /** Totalcost */
            totalCost?: string | null;
        };
        /**
         * CreateWatchlistGroupRequest
         * @description 接收待规范化的新自选分组名称。
         */
        CreateWatchlistGroupRequest: {
            /** Name */
            name: string;
        };
        /**
         * CreateWatchlistItemRequest
         * @description 接收待加入分组的标的和可选备注。
         */
        CreateWatchlistItemRequest: {
            /**
             * Instrumentid
             * Format: uuid
             */
            instrumentId: string;
            /** Note */
            note?: string | null;
        };
        /**
         * Currency
         * @description 表示权威财务值的币种。
         * @enum {string}
         */
        Currency: "CNY";
        /**
         * DataFreshness
         * @description 表示本地数据是否仍在约定的新鲜时间窗口内。
         * @enum {string}
         */
        DataFreshness: "FRESH" | "STALE";
        /**
         * ErrorDetail
         * @description 描述可由客户端稳定匹配的单项 API 错误。
         */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            } | null;
            /** Message */
            message: string;
            /** Requestid */
            requestId: string;
        };
        /**
         * ErrorResponse
         * @description 统一包装 API 错误，供后续全局异常处理中间件复用。
         */
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
        };
        /**
         * EstimatedFundValuationResponse
         * @description 返回明确标记且不进入组合汇总的基金盘中估算。
         */
        EstimatedFundValuationResponse: {
            /** Holdingprofit */
            holdingProfit: string;
            /** Marketvalue */
            marketValue: string;
            price: components["schemas"]["LatestPriceResponse"];
            /** Returnrate */
            returnRate: string;
            /** Todayprofit */
            todayProfit?: string | null;
        };
        /**
         * Exchange
         * @description 区分 A 股交易所与中国公募基金登记域。
         * @enum {string}
         */
        Exchange: "SSE" | "SZSE" | "BSE" | "FUND_CN";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description 定义健康检查的稳定公开响应契约。
         */
        HealthResponse: {
            /** Checks */
            checks?: {
                [key: string]: "ok" | "unavailable";
            } | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "not_ready";
        };
        /**
         * InstrumentListResponse
         * @description 返回稳定分页的资产搜索结果。
         */
        InstrumentListResponse: {
            /** Items */
            items: components["schemas"]["InstrumentResponse"][];
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Total */
            total: number;
        };
        /**
         * InstrumentResponse
         * @description 返回一期资产主数据和互不混淆的最新价格列表。
         */
        InstrumentResponse: {
            assetType: components["schemas"]["AssetType"];
            currency: components["schemas"]["Currency"];
            exchange: components["schemas"]["Exchange"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Latestprices */
            latestPrices: components["schemas"]["LatestPriceResponse"][];
            market: components["schemas"]["Market"];
            /** Name */
            name: string;
            /** Source */
            source: string;
            /** Sourceupdatedat */
            sourceUpdatedAt: string | null;
            /** Ticker */
            ticker: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /**
         * LatestPriceResponse
         * @description 返回一种明确口径的最新价格及其业务时间和抓取时间。
         */
        LatestPriceResponse: {
            /** Asofat */
            asOfAt: string | null;
            /** Asofdate */
            asOfDate: string | null;
            /** Changerate */
            changeRate: string | null;
            /**
             * Fetchedat
             * Format: date-time
             */
            fetchedAt: string;
            freshness: components["schemas"]["DataFreshness"];
            priceType: components["schemas"]["PriceType"];
            /** Source */
            source: string;
            /** Value */
            value: string;
        };
        /**
         * LoginRequest
         * @description 接收登录邮箱和密码，并由服务统一处理错误以防账户枚举。
         */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * ManualMarketDataSyncRequest
         * @description 指定一次人工同步需要执行的一个或多个任务。
         */
        ManualMarketDataSyncRequest: {
            /** Jobtypes */
            jobTypes: components["schemas"]["SyncJobType"][];
        };
        /**
         * ManualMarketDataSyncResponse
         * @description 汇总人工同步结束后的各任务状态和因锁跳过项。
         */
        ManualMarketDataSyncResponse: {
            /**
             * Generatedat
             * Format: date-time
             */
            generatedAt: string;
            /** Jobs */
            jobs: components["schemas"]["MarketDataJobStatusResponse"][];
            /** Skippedjobtypes */
            skippedJobTypes: components["schemas"]["SyncJobType"][];
        };
        /**
         * Market
         * @description 表示资产所属市场，允许后续只新增枚举值。
         * @enum {string}
         */
        Market: "CN";
        /**
         * MarketDataJobStatusResponse
         * @description 返回一种任务最近运行的计数、时间和新鲜度。
         */
        MarketDataJobStatusResponse: {
            /** Failedcount */
            failedCount: number;
            /** Finishedat */
            finishedAt: string | null;
            freshness: components["schemas"]["DataFreshness"];
            jobType: components["schemas"]["SyncJobType"];
            /** Source */
            source: string;
            /**
             * Startedat
             * Format: date-time
             */
            startedAt: string;
            status: components["schemas"]["SyncStatus"];
            /** Succeededcount */
            succeededCount: number;
        };
        /**
         * MarketDataScheduleResponse
         * @description 返回后台同步频率及运行期开关状态。
         */
        MarketDataScheduleResponse: {
            /** Fundestimaterefreshseconds */
            fundEstimateRefreshSeconds: number;
            /** Fundestimatesyncenabled */
            fundEstimateSyncEnabled: boolean;
            /**
             * Instrumentsynctime
             * Format: time
             */
            instrumentSyncTime: string;
            /** Livesyncenabled */
            liveSyncEnabled: boolean;
            /** Officialnavrefreshseconds */
            officialNavRefreshSeconds: number;
            /**
             * Officialnavwindowend
             * Format: time
             */
            officialNavWindowEnd: string;
            /**
             * Officialnavwindowstart
             * Format: time
             */
            officialNavWindowStart: string;
            /** Stockrefreshseconds */
            stockRefreshSeconds: number;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /** Version */
            version: number;
        };
        /**
         * MarketDataStatusResponse
         * @description 返回本地生成时间和已有同步任务的最近状态。
         */
        MarketDataStatusResponse: {
            /**
             * Generatedat
             * Format: date-time
             */
            generatedAt: string;
            /** Jobs */
            jobs: components["schemas"]["MarketDataJobStatusResponse"][];
        };
        /**
         * PasswordResetConfirmRequest
         * @description 接收单次令牌与待校验的新密码。
         */
        PasswordResetConfirmRequest: {
            /** Newpassword */
            newPassword: string;
            /** Token */
            token: string;
        };
        /**
         * PasswordResetRequest
         * @description 接收可能存在或不存在的注册邮箱。
         */
        PasswordResetRequest: {
            /** Email */
            email: string;
        };
        /**
         * PasswordResetRequestResponse
         * @description 返回不泄露邮箱存在性的统一结果。
         */
        PasswordResetRequestResponse: {
            /** Message */
            message: string;
        };
        /**
         * PositionInstrumentResponse
         * @description 返回持仓列表稳定需要的资产身份。
         */
        PositionInstrumentResponse: {
            assetType: components["schemas"]["AssetType"];
            currency: components["schemas"]["Currency"];
            exchange: components["schemas"]["Exchange"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            market: components["schemas"]["Market"];
            /** Name */
            name: string;
            /** Ticker */
            ticker: string;
        };
        /**
         * PositionListResponse
         * @description 返回当前用户持仓的稳定分页列表。
         */
        PositionListResponse: {
            /** Items */
            items: components["schemas"]["PositionResponse"][];
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Total */
            total: number;
        };
        /**
         * PositionResponse
         * @description 返回精简持仓投影、动态估值、资产身份和乐观锁版本。
         */
        PositionResponse: {
            /** Averagecost */
            averageCost: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            estimatedValuation?: components["schemas"]["EstimatedFundValuationResponse"] | null;
            /**
             * Firsttradedate
             * Format: date
             */
            firstTradeDate: string;
            /**
             * Groupid
             * Format: uuid
             */
            groupId: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            instrument: components["schemas"]["PositionInstrumentResponse"];
            /**
             * Lasttradedate
             * Format: date
             */
            lastTradeDate: string;
            /** Quantity */
            quantity: string | null;
            /** Realizedprofit */
            realizedProfit: string;
            status: components["schemas"]["PositionStatus"];
            /** Totalcost */
            totalCost: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            valuation?: components["schemas"]["PositionValuationResponse"] | null;
            /** Version */
            version: number;
        };
        /**
         * PositionStatus
         * @description 表示持仓当前投影是否持有、清仓或等待历史数据补齐。
         * @enum {string}
         */
        PositionStatus: "OPEN" | "CLOSED" | "PENDING";
        /**
         * PositionSummaryResponse
         * @description 返回组合成本、价格完整性和可选权威估值汇总。
         */
        PositionSummaryResponse: {
            /**
             * Calculatedat
             * Format: date-time
             */
            calculatedAt: string;
            /** Estimatedfundpositioncount */
            estimatedFundPositionCount: number;
            /** Groupid */
            groupId: string | null;
            /** Holdingprofit */
            holdingProfit: string | null;
            /** Intradayholdingprofit */
            intradayHoldingProfit: string | null;
            /** Intradaymarketvalue */
            intradayMarketValue: string | null;
            /** Intradayreturnrate */
            intradayReturnRate: string | null;
            /** Marketvalue */
            marketValue: string | null;
            /** Missingpricepositionids */
            missingPricePositionIds: string[];
            /** Positioncount */
            positionCount: number;
            /** Pricedpositioncount */
            pricedPositionCount: number;
            /** Returnrate */
            returnRate: string | null;
            /** Stalepositioncount */
            stalePositionCount: number;
            status: components["schemas"]["ValuationStatus"];
            /** Todayprofit */
            todayProfit?: string | null;
            /**
             * Todayprofitpositioncount
             * @default 0
             */
            todayProfitPositionCount: number;
            /** Totalcost */
            totalCost: string;
        };
        /**
         * PositionValuationResponse
         * @description 返回单只持仓使用的权威价格及精确估值。
         */
        PositionValuationResponse: {
            /** Holdingprofit */
            holdingProfit: string;
            /** Marketvalue */
            marketValue: string;
            price: components["schemas"]["LatestPriceResponse"];
            /** Returnrate */
            returnRate: string;
            /** Settlementupdated */
            settlementUpdated: boolean;
            /** Todayprofit */
            todayProfit?: string | null;
        };
        /**
         * PriceType
         * @description 严格区分股票价格、官方单位净值和盘中估算净值。
         * @enum {string}
         */
        PriceType: "STOCK_LAST" | "FUND_OFFICIAL_NAV" | "FUND_ESTIMATED_NAV";
        /**
         * RegistrationRequest
         * @description 接收待由认证服务完整校验的邮箱和密码原文。
         */
        RegistrationRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * RegistrationResponse
         * @description 返回不含任何密码材料的新用户身份。
         */
        RegistrationResponse: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["UserStatus"];
        };
        /**
         * SessionResponse
         * @description 返回当前会话对应且不含凭据的用户身份。
         */
        SessionResponse: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["UserStatus"];
        };
        /**
         * SyncJobType
         * @description 标识 Worker 执行的独立同步任务。
         * @enum {string}
         */
        SyncJobType: "INSTRUMENT_MASTER" | "STOCK_PRICES" | "FUND_OFFICIAL_NAV" | "FUND_ESTIMATED_NAV";
        /**
         * SyncStatus
         * @description 表示同步任务完整生命周期。
         * @enum {string}
         */
        SyncStatus: "RUNNING" | "SUCCEEDED" | "PARTIAL" | "FAILED";
        /**
         * UpdateFundAmountPositionRequest
         * @description 接收带版本号的基金金额模式部分更新。
         */
        UpdateFundAmountPositionRequest: {
            /** Currentvalue */
            currentValue?: string | null;
            /** Groupid */
            groupId?: string | null;
            /** Holdingprofit */
            holdingProfit?: string | null;
            /** Inputdate */
            inputDate?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            inputMode: "FUND_AMOUNT";
            /** Version */
            version: number;
        };
        /**
         * UpdateFundSharesPositionRequest
         * @description 接收带版本号的基金份额模式部分更新。
         */
        UpdateFundSharesPositionRequest: {
            /** Averagecost */
            averageCost?: string | null;
            costInputMode?: components["schemas"]["CostInputMode"] | null;
            /** Groupid */
            groupId?: string | null;
            /** Inputdate */
            inputDate?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            inputMode: "FUND_SHARES";
            /** Quantity */
            quantity?: string | null;
            /** Totalcost */
            totalCost?: string | null;
            /** Version */
            version: number;
        };
        /**
         * UpdateMarketDataScheduleRequest
         * @description 校验用户可修改的全站行情调度配置。
         */
        UpdateMarketDataScheduleRequest: {
            /** Fundestimaterefreshseconds */
            fundEstimateRefreshSeconds: number;
            /**
             * Instrumentsynctime
             * Format: time
             */
            instrumentSyncTime: string;
            /** Officialnavrefreshseconds */
            officialNavRefreshSeconds: number;
            /**
             * Officialnavwindowend
             * Format: time
             */
            officialNavWindowEnd: string;
            /**
             * Officialnavwindowstart
             * Format: time
             */
            officialNavWindowStart: string;
            /** Stockrefreshseconds */
            stockRefreshSeconds: number;
        };
        /**
         * UpdateStockPositionRequest
         * @description 接收带版本号的股票持仓部分更新。
         */
        UpdateStockPositionRequest: {
            /** Averagecost */
            averageCost?: string | null;
            costInputMode?: components["schemas"]["CostInputMode"] | null;
            /** Groupid */
            groupId?: string | null;
            /** Inputdate */
            inputDate?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            inputMode: "STOCK_SHARES";
            /** Quantity */
            quantity?: string | null;
            /** Totalcost */
            totalCost?: string | null;
            /** Version */
            version: number;
        };
        /**
         * UpdateWatchlistGroupRequest
         * @description 使用版本号选择性修改分组名称或排序。
         */
        UpdateWatchlistGroupRequest: {
            /** Name */
            name?: string | null;
            /** Sortorder */
            sortOrder?: number | null;
            /** Version */
            version: number;
        };
        /**
         * UpdateWatchlistItemRequest
         * @description 使用版本号选择性移动、修改备注或调整排序。
         */
        UpdateWatchlistItemRequest: {
            /** Groupid */
            groupId?: string | null;
            /** Note */
            note?: string | null;
            /** Sortorder */
            sortOrder?: number | null;
            /** Version */
            version: number;
        };
        /**
         * UserStatus
         * @description 表示用户是否可以创建新会话。
         * @enum {string}
         */
        UserStatus: "ACTIVE" | "DISABLED";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * ValuationStatus
         * @description 表示组合估值是否完整、陈旧或为空。
         * @enum {string}
         */
        ValuationStatus: "COMPLETE" | "STALE" | "INCOMPLETE" | "EMPTY";
        /**
         * WatchlistGroupListResponse
         * @description 返回当前用户全部自选分组。
         */
        WatchlistGroupListResponse: {
            /** Items */
            items: components["schemas"]["WatchlistGroupResponse"][];
        };
        /**
         * WatchlistGroupResponse
         * @description 返回用户可见的统一分组及自选、持仓数量。
         */
        WatchlistGroupResponse: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Isdefault */
            isDefault: boolean;
            /** Itemcount */
            itemCount: number;
            /** Name */
            name: string;
            /** Positioncount */
            positionCount: number;
            /** Sortorder */
            sortOrder: number;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /** Version */
            version: number;
        };
        /**
         * WatchlistItemListResponse
         * @description 返回指定分组的稳定分页观察标的列表。
         */
        WatchlistItemListResponse: {
            /** Items */
            items: components["schemas"]["WatchlistItemResponse"][];
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Total */
            total: number;
        };
        /**
         * WatchlistItemResponse
         * @description 返回观察标的、所属分组、备注、行情和乐观锁版本。
         */
        WatchlistItemResponse: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Groupid
             * Format: uuid
             */
            groupId: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            instrument: components["schemas"]["InstrumentResponse"];
            /** Note */
            note: string | null;
            /** Sortorder */
            sortOrder: number;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /** Version */
            version: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_ai_conversation_api_v1_ai_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIConversationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_ai_conversation_message_api_v1_ai_conversations__conversation_id__messages_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AIConversationMessageCreate"];
            };
        };
        responses: {
            /** @description Codex Agent 增量事件流 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_password_reset_api_v1_auth_password_reset_requests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasswordResetRequestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_api_v1_auth_password_resets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_v1_auth_registrations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    current_session_api_v1_auth_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout_api_v1_auth_session_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login_api_v1_auth_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_api_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    search_instruments_api_v1_instruments_get: {
        parameters: {
            query?: {
                query?: string | null;
                assetType?: components["schemas"]["AssetType"] | null;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_instrument_api_v1_instruments__instrument_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instrument_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ai_analysis_api_v1_instruments__instrument_id__ai_analysis_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instrument_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIAnalysisResponse"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_ai_analysis_api_v1_instruments__instrument_id__ai_analysis_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instrument_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIAnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_ai_conversation_api_v1_instruments__instrument_id__ai_conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instrument_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIConversationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_latest_ai_conversation_api_v1_instruments__instrument_id__ai_conversations_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instrument_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIConversationResponse"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_market_data_schedule_api_v1_market_data_schedule_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketDataScheduleResponse"];
                };
            };
        };
    };
    update_market_data_schedule_api_v1_market_data_schedule_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMarketDataScheduleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketDataScheduleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_market_data_status_api_v1_market_data_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketDataStatusResponse"];
                };
            };
        };
    };
    manually_sync_market_data_api_v1_market_data_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualMarketDataSyncRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualMarketDataSyncResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_position_summary_api_v1_position_summary_get: {
        parameters: {
            query?: {
                groupId?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_positions_api_v1_positions_get: {
        parameters: {
            query?: {
                groupId?: string | null;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_position_api_v1_positions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStockPositionRequest"] | components["schemas"]["CreateFundAmountPositionRequest"] | components["schemas"]["CreateFundSharesPositionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_position_api_v1_positions__position_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_position_api_v1_positions__position_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_position_api_v1_positions__position_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                position_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStockPositionRequest"] | components["schemas"]["UpdateFundAmountPositionRequest"] | components["schemas"]["UpdateFundSharesPositionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_watchlist_groups_api_v1_watchlist_groups_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistGroupListResponse"];
                };
            };
        };
    };
    create_watchlist_group_api_v1_watchlist_groups_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWatchlistGroupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistGroupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_watchlist_group_api_v1_watchlist_groups__group_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistGroupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_watchlist_group_api_v1_watchlist_groups__group_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_watchlist_group_api_v1_watchlist_groups__group_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWatchlistGroupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistGroupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_watchlist_items_api_v1_watchlist_groups__group_id__items_get: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistItemListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_watchlist_item_api_v1_watchlist_groups__group_id__items_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWatchlistItemRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_watchlist_item_api_v1_watchlist_items__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_watchlist_item_api_v1_watchlist_items__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_watchlist_item_api_v1_watchlist_items__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWatchlistItemRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
